name: ai-agent-n8n
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - openai==1.3.0
    - python-dotenv==1.0.0
    - requests==2.31.0 